# This is a workflow to generate a snake-style GitHub contribution graph GIF

name: Generate Snake

# Controls when the workflow will run
on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Generate the Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: akdwivedi-explorer  # Your GitHub username
          output_filename: github-contribution-grid-snake.gif
          color_snake: orange
          color_dots: "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Update snake animations"
          add: 'dist/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
